### ISSUE TITLE
Does not work in WSL2

### ISSUE THREAD

**Issue by lopes-gustavo** [Ashald/EnvFile#164]
If I have Goland installed in Windows and using my project under WSL, this plugin won't load the variables (maybe it will, but probably in another environment).

I don't know how to debug to provide more info, but I'm willing to do so if someone guide me through.

**Comment by kato-m** [comment]
I am on PyCharm 2021.3 (build #PY-213.5744.248) and experiencing the same issue.

**Comment by davidmnoriega** [comment]
Using IntelliJ Ultimate with a Run Target to tasks in wsl2 and also confirm they dont get any environment vars from EnvFile

**Comment by Deliganli** [comment]
IntelliJ Ultimate, 2021.3, WSL2 Ubuntu. Same issue

**Comment by ArtemZip** [comment]
Could not set the value of environment variable '=::': could not putenv() (errno 22: Invalid argument)

**Comment by Claudio-code** [comment]
IntelliJ Ultimate, 2022.1.2, WSL2 Debian same issue

**Comment by nello** [comment]
Trying to use this for Java in IntelliJ Ultimate 2022.1.2 it doesn't seem to do ... anything. No environment variables in my `.env` file are actually set in my run configuration, no matter what I do.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/966106/174933600-653fbe9d-d972-48ee-9261-72163a512bf9.png">

`TP_FIREBASE_URL` is pretty much the *first* variable set in my `.env` file.
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/966106/174934107-864b4af5-2fd1-4340-a5f2-72c7022e0df6.png">

**Comment by ashald** [comment]
Should be fixed in 3.4.1

**Comment by PrinzEugen212** [comment]
Still don't working on Goland in WSL2 Ubuntu

**Comment by VishalDalwadi** [comment]
Not working on Goland in WSL2. Any fix for this? Or workaround?

**Comment by Kirdock** [comment]
@ashald this is still an issue with Go. Seems like it's not working for GoLand & WSL2.
For me, I can tell that it doesn't work when running `Go Build` or `Go Test` with IntelliJ Ultimate + WSL2
